version: '3'

services:
  janus:
    image: janusgraph:0.2.0-hadoop2
    build:
      dockerfile: Dockerfile.janus
      args:
        version: 0.2.0
        hadoop: hadoop2
      context: ./
    ports:
      - "8182:8182"
      - "8184:8184"
    depends_on:
      - db
      - index
    command: ["/bin/bash", "-e", "/workspace/janusgraph/run.sh"]
  db:
    image: cassandra:latest
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_START_RPC=true
    ports:
      - "7199:7199" # JMX
      - "7000:7000" # cluster communication
      - "7001:7001" # cluster communication (SSL)
      - "9042:9042" # native protocol clients
      - "9160:9160" # thrift clients
      # Prometheus monitoring
      - "9180:9180"
      - "9100:9100"
  index:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    ports:
     - "9200:9200"
     - "9300:9300"